### ISSUE TITLE
Gemfile: Ruby version 2.2.0 required

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-blog-nested-forms#11]
When I ran bundle install I got this message:
```
14:52:28] (master) rails-blog-nested-forms-v-000
// ♥ bundle install
Your Ruby version is 2.2.3, but your Gemfile specified 2.2.0
[14:52:53] (master) rails-blog-nested-forms-v-000
// ♥ rvm install ruby-2.2.0
```

After installing 2.2.0, I tried running learn and got this:
```
// ♥ learn
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'learn-co' (>= 0) among 16 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/learn:22:in `<main>'
```

I don't know if I did something wrong, but if I just set the Gemfile to my current Ruby version:

```
ruby '2.2.3'
```

and everything seems to be running well. I checked another student (who completed the lab already) and they had changed it to 2.2.3, too.

**Comment by pletcher** [comment]
Changing the Gemfile version is probably fine. The issue is that you'd need to install `learn-co` on v2.2.0 as well.

Aspirationally, I'd love to find a way to fix these Bundler issues (I'm running into them daily). Someday.
