### ISSUE TITLE
FYI tests can pass even if the program is broken

### ISSUE THREAD

**Issue by NoneOfMaster** [learn-co-curriculum/rails-blog-nested-forms#13]
I had it broken a few different ways before I solved it so that it was working nicely in my browser, but after my tests were already passing. One example below:
![screen shot 2016-02-02 at 2 27 30 pm](https://cloud.githubusercontent.com/assets/12436033/12769115/cd115308-c9c9-11e5-8fb9-dbd81318406a.png)

**Comment by jmburges** [comment]
Take a look at NoneOfMaster's solution and maybe figure out why his passes

**Comment by pletcher** [comment]
At least for this specific case, it looks like we aren't testing that tags are unique even though we mention the uniqueness constraint in the README.

I'll add tests :)
