### ISSUE TITLE
Learn Command isn't working

### ISSUE THREAD

**Issue by ShanaLMoore** [learn-co-curriculum/rails-blog-nested-forms#14]
I can't get my tests working. I've tried to delete the gem file.lockm reinstall bundler and reinstall learn-co.

**Comment by AnnJohn** [comment]
Hi @ShanaLMoore we'll look into this and keep the issue open. For now a possible solution could be to update your Gemfile to your current ruby version. Thanks!

**Comment by AnnJohn** [comment]
hi @ShanaLMoore have you tried updating your rub

**Comment by pletcher** [comment]
Hi @ShanaLMoore, could you paste the error that you're getting here?

**Comment by pletcher** [comment]
I've closed this for now, but feel free to reopen if it continues to be a problem!
