### ISSUE TITLE
Please update Ruby version in Gemfile to 2.2.1

### ISSUE THREAD

**Issue by fiveinfinity** [learn-co-curriculum/rails-blog-nested-forms#18]
bundle install and learn won't work properly with 2.2.0 currently. Thanks!

**Comment by PeterBell** [comment]
Wanted to update this as someone else noted the Gemfile requires ruby 2.2.0 and wondered if they'd have to downgrade ruby. Wondering if we should just remove the line from the Gemfile or be explicit in the README to update the version? Especially as I don't *think* you can just specify a minimum ruby version in a Gemfile unlike minimum versions of gems (best link I found quickly was http://stackoverflow.com/questions/28440712/how-can-i-specify-a-minimum-ruby-version-in-a-gemfile )

Would love an opinion @pletcher and/or @jmburges  (cc @AnnJohn ). I'm happy to make whatever fix you prefer . . .

**Comment by pletcher** [comment]
Yeah, I think the Gemfile version (and .ruby-version version for that matter) are pretty strict. 

I'm okay just removing it, but I worry about other issues that that might cause. Students should have RVM and be able to switch versions pretty easily -- I'll give this a think this weekend (might be easier to hash out in person on Monday).

**Comment by pletcher** [comment]
Could we be explicit in the README that students might need to switch their current Ruby version using RVM? @PeterBell

**Comment by AnnJohn** [comment]
@PeterBell just wanted to get your opinion on Chuck's question. thanks.

**Comment by PeterBell** [comment]
Hey, sorry for the slow response @pletcher and @AnnJohn - my main concern is that (most) everyone will run into this issue whereas only a small number of people will run into issues running old versions of ruby.

Possible solutions:
1. We just update this to be whatever ruby-latest is now and have a script to update it everywhere every time there's a new ruby stable
2. We tell people explicitly in the readme to use RVM and to change rubies. But are we sure we're using rvm in the ILE (I just don't know) and have we taught it (I didn't immediately see it in the curriculum but it may be there)
3. We remove this and deal with any issues if someone happens to be running 1.8.7 EE or whatever

I'm open to any of the 3 although the third option feels like it might be quickest and simplest fix for now. Thoughts?!

**Comment by pletcher** [comment]
That's fair -- let's go with option 3 :)

**Comment by PeterBell** [comment]
See PR @pletcher !

**Comment by pletcher** [comment]
👍
