### ISSUE TITLE
Instructions do not match the assignment.

### ISSUE THREAD

**Issue by WilliamBarela** [learn-co-curriculum/rails-blog-nested-forms#22]
Hi, I just wanted to point out that the instructions for this lab only vaguely match what the student is supposed to do. There are also a lot of junk files (_form.html.erb AND form.html.erb intead of just the former).

**Comment by gj** [comment]
Hi @WilliamBarela !

Mind expanding on what you mean by `the instructions for this lab only vaguely match what the student is supposed to do`?

Can definitely delete the junk files, but I'd like to get a better sense of what your other issue is first. 🙂

**Comment by WilliamBarela** [comment]
Hi @gj! 

This is my pull request: https://github.com/learn-co-students/rails-blog-nested-forms-v-000/pull/328/files. As you can see, I successfully passed the lab; however, the first instruction given is this:

> Before anything, when you generate models, controllers, etc., be sure to include the --no-test-framework option so that it skips tests (which we already have).

I appreciate the need to use the --no-test-framework flag, but as you can see from my pull request, there was no need to generate models, controllers or any other rails generator for that matter as these were already included in the lab.

Perhaps my reaction was a little strong, but that issue combined with the fact that the folder was set up for use with partials (which were foreign to me at the time because we had not yet covered them), lead me to see this lab as very confusing.

I think I would not be the only person to feel this way (at at point in the curriculum), so maybe my recommendation is just to simplify the lab to exclude the use of the partials, and maybe exclude the mention of the generators (since they are not necessary here).

**Comment by gj** [comment]
@WilliamBarela thanks so much for the detailed response! I can definitely understand the reaction, and your point about including yet-to-be-introduced concepts is a good one. Have to back-burner this for now, but I'll leave the issue open to remind myself (and others).

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
