### ISSUE TITLE
Issue with `post_spec.rb` test

### ISSUE THREAD

**Issue by saurookadook** [learn-co-curriculum/rails-blog-nested-forms#23]
I believe line 11 in the tests should only be `tags_attributes: {}` instead of `tags_attributes [{}]`. With the original line given in the tests, it raises an error which requires extra steps in the `tags_attributes=` method which you normally would not need, since Rails would pass the argument for that method as a hash rather than an array with a hash.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
