### ISSUE TITLE
Points of confusion

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/rails-blog-nested-forms#24]
There are a few things in the instructions for this lab that are confusing.
1) The first part of #5 sounds like it's talking about the need to create a custom attribute writer that incorporates find_or_create_by, but that doesn't seem like it has anything to do with whether a user has to submit a new tag every time they submit a post. Should the second half of the sentence be a separate point #6?
2) Partly because of this confusion, the code snippet is also confusing -- based on placement, it seems like it should be related to the uniqueness validation. The fact that it uses User and Post as an example -- models that are in the lab but are not where the code needs to be included -- adds to the confusion. 
3) I believe the last item (labeled 1 but really 6) should say "... the controller action for a new **post** ... " instead. 

Also, all of the tests pass without the custom attribute writer. With the custom attribute writer, one test fails (the first test in /spec/models/post_spec.rb), as described in issue #23

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
